pipeline {
    agent any

    tools {
        go 'Go 1.16'  // Ensure Go is installed and configured in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/charan-happy/MyApp.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('go-app') {
                    sh 'go mod download'
                }
            }
        }
        stage('Lint') {
            steps {
                dir('go-app') {
                    sh 'go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest'
                    sh 'golangci-lint run'
                }
            }
        }
        stage('Test') {
            steps {
                dir('go-app') {
                    sh 'go test ./...'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('go-app') {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials-id'){
                        def app = docker.build("charan63/go-app")
                        app.push()
                    }
                    }
                }
            }
        }
    }
}
