name: Go CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./...

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run Linter
      run: golangci-lint run

    - name: Dockerhub Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.Dockerhub_USERNAME }}
        password: ${{ secrets.Dockerhub_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.Dockerhub_USERNAME }}/go-app .

    - name: Push Docker image
      run: docker push ${{ secrets.Dockerhub_USERNAME }}/go-app
