name: Go CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install dependencies 
      run: go mod init .
    - name: Run Linter
      run: golangci-lint run
    - name: Test
      run: go test ./...
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    
    - name: Dockerhub Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ vars.Dockerhub_USERNAME }}
        password: ${{ secrets.Dockerhub_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ vars.Dockerhub_USERNAME }}/go-app .
    - name: Push Docker image
      run: docker push ${{ vars.Dockerhub_USERNAME }}/go-app
    
    
