name: Go CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install dependencies
      run: go mod download go-app
      # linting
    - name: Lint
      run: golangci-Lint run
      # testing
    - name: Test
      run: go test ./...

    - name: Install golangci-lint
      run: go Install github.com/golangci/golangci-lint/cmd/golangci@latest

    - name: Build Docker image
      run: docker build -t ${ secrets.DOCKERHUB_USERNAME }/go-app .
    - name: Push Docker image
      run: docker push ${ secrets.DOCKERHUB_USERNAME }/go-app 
