name: WordPress CI

on:
  workflow_dispatch:
  
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install dependencies
      run: cd wordpress-app && composer install
    - name: Test
      run: cd wordpress-app && phpunit
    - name: Dockerhub Login
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build Docker image
      run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/wordpress-app ./wordpress-app
    - name: Push Docker image
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/wordpress-app
