name: WordPress CI

on:
  push:
    branches: [main]
    paths-ignore: 
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - run: sudo apt-get install -y unzip
    - run: curl -LO https://github.com/squizlabs/PHP_CodeSniffer/releases/download/3.6.0/phpcs.phar
    - run: chmod +x phpcs.phar
    - run: mv phpcs.phar /usr/local/bin/phpcs
    - run: phpcs --config-set installed_paths /path/to/wordpress-coding-standards
    - run: phpcs --standard=WordPress .
    - run: composer install
    - run: ./vendor/bin/phpcs --standard=WordPress .
    - run: composer require --dev squizlabs/php_codesniffer ; vendor/bin/phpcs --config-set installed_paths /path/to/wordpress-coding-standards

    - name: Dockerhub Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ vars.Dockerhub_USERNAME }}
        password: ${{ secrets.Dockerhub_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ vars.Dockerhub_USERNAME }}/go-app .
    - name: Push Docker image
      run: docker push ${{ vars.Dockerhub_USERNAME }}/go-app
    
